import random

import pytest

import board_generator, ai


PLAYER_BOARD_SHIPS = ({'x': 5, 'y': 0},
                      {'x': 7, 'y': 2}, {'x': 7, 'y': 6},
                      {'x': 9, 'y': 4},
                      {'x': 0, 'y': 1}, {'x': 2, 'y': 8}, {'x': 5, 'y': 6},
                      {'x': 0, 'y': 6}, {'x': 2, 'y': 1},
                      {'x': 3, 'y': 4}, {'x': 3, 'y': 6})
PLAYER_BOARD_ORIENTATIONS = ('horizontal', 'vertical', 'horizontal',
                             'vertical', 'horizontal', 'vertical',
                             'vertical', 'vertical', 'vertical', 'vertical')
ENEMY_BOARD_SHIPS = ({'x': 6, 'y': 2},
                     {'x': 1, 'y': 4}, {'x': 2, 'y': 0},
                     {'x': 4, 'y': 4}, {'x': 4, 'y': 6}, {'x': 7, 'y': 9},
                     {'x': 1, 'y': 9}, {'x': 4, 'y': 0},
                     {'x': 5, 'y': 9}, {'x': 7, 'y': 0})
ENEMY_BOARD_ORIENTATIONS = ('horizontal', 'vertical', 'vertical',
                            'horizontal', 'horizontal', 'horizontal',
                            'vertical', 'vertical', 'vertical', 'vertical',)
AI_ATTACK_DIRECTIONS = ('up', 'down', 'left', 'right')
AI_MOVES = (1, 2, 3, 4, 5)


@pytest.fixture()
def player_board_params():
    player_board_params = {'width_in_tiles': 10,
                           'height_in_tiles': 10,
                           'topleft': (92, 160),
                           'grid_step': 40,
                           'grid_width': 2,
                           'empty_tile_color': (3, 54, 73)}
    return player_board_params


@pytest.fixture()
def enemy_board_params():
    enemy_board_params = {'width_in_tiles': 10,
                          'height_in_tiles': 10,
                          'topleft': (532, 160),
                          'grid_step': 40,
                          'grid_width': 2,
                          'empty_tile_color': (3, 54, 73)}
    return enemy_board_params


@pytest.fixture()
def new_player_board():
    new_player_board = {'tiles': [[{'pixel_x': 94, 'pixel_y': 162, 'board_x': 0, 'board_y': 0, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 94, 'pixel_y': 202, 'board_x': 0, 'board_y': 1, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 94, 'pixel_y': 242, 'board_x': 0, 'board_y': 2, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 94, 'pixel_y': 282, 'board_x': 0, 'board_y': 3, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 94, 'pixel_y': 322, 'board_x': 0, 'board_y': 4, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 94, 'pixel_y': 362, 'board_x': 0, 'board_y': 5, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 94, 'pixel_y': 402, 'board_x': 0, 'board_y': 6, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 94, 'pixel_y': 442, 'board_x': 0, 'board_y': 7, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 94, 'pixel_y': 482, 'board_x': 0, 'board_y': 8, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 94, 'pixel_y': 522, 'board_x': 0, 'board_y': 9, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}],
                                  [{'pixel_x': 134, 'pixel_y': 162, 'board_x': 1, 'board_y': 0, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 134, 'pixel_y': 202, 'board_x': 1, 'board_y': 1, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 134, 'pixel_y': 242, 'board_x': 1, 'board_y': 2, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 134, 'pixel_y': 282, 'board_x': 1, 'board_y': 3, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 134, 'pixel_y': 322, 'board_x': 1, 'board_y': 4, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 134, 'pixel_y': 362, 'board_x': 1, 'board_y': 5, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 134, 'pixel_y': 402, 'board_x': 1, 'board_y': 6, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 134, 'pixel_y': 442, 'board_x': 1, 'board_y': 7, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 134, 'pixel_y': 482, 'board_x': 1, 'board_y': 8, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 134, 'pixel_y': 522, 'board_x': 1, 'board_y': 9, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}],
                                  [{'pixel_x': 174, 'pixel_y': 162, 'board_x': 2, 'board_y': 0, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 174, 'pixel_y': 202, 'board_x': 2, 'board_y': 1, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 174, 'pixel_y': 242, 'board_x': 2, 'board_y': 2, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 174, 'pixel_y': 282, 'board_x': 2, 'board_y': 3, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 174, 'pixel_y': 322, 'board_x': 2, 'board_y': 4, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 174, 'pixel_y': 362, 'board_x': 2, 'board_y': 5, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 174, 'pixel_y': 402, 'board_x': 2, 'board_y': 6, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 174, 'pixel_y': 442, 'board_x': 2, 'board_y': 7, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 174, 'pixel_y': 482, 'board_x': 2, 'board_y': 8, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 174, 'pixel_y': 522, 'board_x': 2, 'board_y': 9, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}],
                                  [{'pixel_x': 214, 'pixel_y': 162, 'board_x': 3, 'board_y': 0, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 214, 'pixel_y': 202, 'board_x': 3, 'board_y': 1, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 214, 'pixel_y': 242, 'board_x': 3, 'board_y': 2, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 214, 'pixel_y': 282, 'board_x': 3, 'board_y': 3, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 214, 'pixel_y': 322, 'board_x': 3, 'board_y': 4, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 214, 'pixel_y': 362, 'board_x': 3, 'board_y': 5, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 214, 'pixel_y': 402, 'board_x': 3, 'board_y': 6, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 214, 'pixel_y': 442, 'board_x': 3, 'board_y': 7, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 214, 'pixel_y': 482, 'board_x': 3, 'board_y': 8, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 214, 'pixel_y': 522, 'board_x': 3, 'board_y': 9, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}],
                                  [{'pixel_x': 254, 'pixel_y': 162, 'board_x': 4, 'board_y': 0, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 254, 'pixel_y': 202, 'board_x': 4, 'board_y': 1, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 254, 'pixel_y': 242, 'board_x': 4, 'board_y': 2, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 254, 'pixel_y': 282, 'board_x': 4, 'board_y': 3, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 254, 'pixel_y': 322, 'board_x': 4, 'board_y': 4, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 254, 'pixel_y': 362, 'board_x': 4, 'board_y': 5, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 254, 'pixel_y': 402, 'board_x': 4, 'board_y': 6, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 254, 'pixel_y': 442, 'board_x': 4, 'board_y': 7, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 254, 'pixel_y': 482, 'board_x': 4, 'board_y': 8, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 254, 'pixel_y': 522, 'board_x': 4, 'board_y': 9, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}],
                                  [{'pixel_x': 294, 'pixel_y': 162, 'board_x': 5, 'board_y': 0, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 294, 'pixel_y': 202, 'board_x': 5, 'board_y': 1, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 294, 'pixel_y': 242, 'board_x': 5, 'board_y': 2, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 294, 'pixel_y': 282, 'board_x': 5, 'board_y': 3, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 294, 'pixel_y': 322, 'board_x': 5, 'board_y': 4, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 294, 'pixel_y': 362, 'board_x': 5, 'board_y': 5, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 294, 'pixel_y': 402, 'board_x': 5, 'board_y': 6, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 294, 'pixel_y': 442, 'board_x': 5, 'board_y': 7, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 294, 'pixel_y': 482, 'board_x': 5, 'board_y': 8, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 294, 'pixel_y': 522, 'board_x': 5, 'board_y': 9, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}],
                                  [{'pixel_x': 334, 'pixel_y': 162, 'board_x': 6, 'board_y': 0, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 334, 'pixel_y': 202, 'board_x': 6, 'board_y': 1, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 334, 'pixel_y': 242, 'board_x': 6, 'board_y': 2, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 334, 'pixel_y': 282, 'board_x': 6, 'board_y': 3, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 334, 'pixel_y': 322, 'board_x': 6, 'board_y': 4, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 334, 'pixel_y': 362, 'board_x': 6, 'board_y': 5, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 334, 'pixel_y': 402, 'board_x': 6, 'board_y': 6, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 334, 'pixel_y': 442, 'board_x': 6, 'board_y': 7, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 334, 'pixel_y': 482, 'board_x': 6, 'board_y': 8, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 334, 'pixel_y': 522, 'board_x': 6, 'board_y': 9, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}],
                                  [{'pixel_x': 374, 'pixel_y': 162, 'board_x': 7, 'board_y': 0, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 374, 'pixel_y': 202, 'board_x': 7, 'board_y': 1, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 374, 'pixel_y': 242, 'board_x': 7, 'board_y': 2, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 374, 'pixel_y': 282, 'board_x': 7, 'board_y': 3, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 374, 'pixel_y': 322, 'board_x': 7, 'board_y': 4, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 374, 'pixel_y': 362, 'board_x': 7, 'board_y': 5, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 374, 'pixel_y': 402, 'board_x': 7, 'board_y': 6, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 374, 'pixel_y': 442, 'board_x': 7, 'board_y': 7, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 374, 'pixel_y': 482, 'board_x': 7, 'board_y': 8, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 374, 'pixel_y': 522, 'board_x': 7, 'board_y': 9, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}],
                                  [{'pixel_x': 414, 'pixel_y': 162, 'board_x': 8, 'board_y': 0, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 414, 'pixel_y': 202, 'board_x': 8, 'board_y': 1, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 414, 'pixel_y': 242, 'board_x': 8, 'board_y': 2, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 414, 'pixel_y': 282, 'board_x': 8, 'board_y': 3, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 414, 'pixel_y': 322, 'board_x': 8, 'board_y': 4, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 414, 'pixel_y': 362, 'board_x': 8, 'board_y': 5, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 414, 'pixel_y': 402, 'board_x': 8, 'board_y': 6, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 414, 'pixel_y': 442, 'board_x': 8, 'board_y': 7, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 414, 'pixel_y': 482, 'board_x': 8, 'board_y': 8, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 414, 'pixel_y': 522, 'board_x': 8, 'board_y': 9, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}],
                                  [{'pixel_x': 454, 'pixel_y': 162, 'board_x': 9, 'board_y': 0, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 454, 'pixel_y': 202, 'board_x': 9, 'board_y': 1, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 454, 'pixel_y': 242, 'board_x': 9, 'board_y': 2, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 454, 'pixel_y': 282, 'board_x': 9, 'board_y': 3, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 454, 'pixel_y': 322, 'board_x': 9, 'board_y': 4, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 454, 'pixel_y': 362, 'board_x': 9, 'board_y': 5, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 454, 'pixel_y': 402, 'board_x': 9, 'board_y': 6, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 454, 'pixel_y': 442, 'board_x': 9, 'board_y': 7, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 454, 'pixel_y': 482, 'board_x': 9, 'board_y': 8, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 454, 'pixel_y': 522, 'board_x': 9, 'board_y': 9, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}]],
                        'topleft': {'pixel_x': 92, 'pixel_y': 160},
                        'targets': []}
    return new_player_board


@pytest.fixture()
def new_enemy_board():
    new_enemy_board = {'tiles': [[{'pixel_x': 534, 'pixel_y': 162, 'board_x': 0, 'board_y': 0, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 534, 'pixel_y': 202, 'board_x': 0, 'board_y': 1, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 534, 'pixel_y': 242, 'board_x': 0, 'board_y': 2, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 534, 'pixel_y': 282, 'board_x': 0, 'board_y': 3, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 534, 'pixel_y': 322, 'board_x': 0, 'board_y': 4, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 534, 'pixel_y': 362, 'board_x': 0, 'board_y': 5, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 534, 'pixel_y': 402, 'board_x': 0, 'board_y': 6, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 534, 'pixel_y': 442, 'board_x': 0, 'board_y': 7, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 534, 'pixel_y': 482, 'board_x': 0, 'board_y': 8, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 534, 'pixel_y': 522, 'board_x': 0, 'board_y': 9, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}],
                                 [{'pixel_x': 574, 'pixel_y': 162, 'board_x': 1, 'board_y': 0, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 574, 'pixel_y': 202, 'board_x': 1, 'board_y': 1, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 574, 'pixel_y': 242, 'board_x': 1, 'board_y': 2, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 574, 'pixel_y': 282, 'board_x': 1, 'board_y': 3, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 574, 'pixel_y': 322, 'board_x': 1, 'board_y': 4, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 574, 'pixel_y': 362, 'board_x': 1, 'board_y': 5, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 574, 'pixel_y': 402, 'board_x': 1, 'board_y': 6, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 574, 'pixel_y': 442, 'board_x': 1, 'board_y': 7, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 574, 'pixel_y': 482, 'board_x': 1, 'board_y': 8, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 574, 'pixel_y': 522, 'board_x': 1, 'board_y': 9, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}],
                                 [{'pixel_x': 614, 'pixel_y': 162, 'board_x': 2, 'board_y': 0, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 614, 'pixel_y': 202, 'board_x': 2, 'board_y': 1, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 614, 'pixel_y': 242, 'board_x': 2, 'board_y': 2, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 614, 'pixel_y': 282, 'board_x': 2, 'board_y': 3, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 614, 'pixel_y': 322, 'board_x': 2, 'board_y': 4, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 614, 'pixel_y': 362, 'board_x': 2, 'board_y': 5, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 614, 'pixel_y': 402, 'board_x': 2, 'board_y': 6, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 614, 'pixel_y': 442, 'board_x': 2, 'board_y': 7, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 614, 'pixel_y': 482, 'board_x': 2, 'board_y': 8, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 614, 'pixel_y': 522, 'board_x': 2, 'board_y': 9, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}],
                                 [{'pixel_x': 654, 'pixel_y': 162, 'board_x': 3, 'board_y': 0, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 654, 'pixel_y': 202, 'board_x': 3, 'board_y': 1, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 654, 'pixel_y': 242, 'board_x': 3, 'board_y': 2, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 654, 'pixel_y': 282, 'board_x': 3, 'board_y': 3, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 654, 'pixel_y': 322, 'board_x': 3, 'board_y': 4, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 654, 'pixel_y': 362, 'board_x': 3, 'board_y': 5, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 654, 'pixel_y': 402, 'board_x': 3, 'board_y': 6, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 654, 'pixel_y': 442, 'board_x': 3, 'board_y': 7, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 654, 'pixel_y': 482, 'board_x': 3, 'board_y': 8, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 654, 'pixel_y': 522, 'board_x': 3, 'board_y': 9, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}],
                                 [{'pixel_x': 694, 'pixel_y': 162, 'board_x': 4, 'board_y': 0, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 694, 'pixel_y': 202, 'board_x': 4, 'board_y': 1, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 694, 'pixel_y': 242, 'board_x': 4, 'board_y': 2, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 694, 'pixel_y': 282, 'board_x': 4, 'board_y': 3, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 694, 'pixel_y': 322, 'board_x': 4, 'board_y': 4, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 694, 'pixel_y': 362, 'board_x': 4, 'board_y': 5, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 694, 'pixel_y': 402, 'board_x': 4, 'board_y': 6, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 694, 'pixel_y': 442, 'board_x': 4, 'board_y': 7, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 694, 'pixel_y': 482, 'board_x': 4, 'board_y': 8, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 694, 'pixel_y': 522, 'board_x': 4, 'board_y': 9, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}],
                                 [{'pixel_x': 734, 'pixel_y': 162, 'board_x': 5, 'board_y': 0, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 734, 'pixel_y': 202, 'board_x': 5, 'board_y': 1, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 734, 'pixel_y': 242, 'board_x': 5, 'board_y': 2, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 734, 'pixel_y': 282, 'board_x': 5, 'board_y': 3, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 734, 'pixel_y': 322, 'board_x': 5, 'board_y': 4, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 734, 'pixel_y': 362, 'board_x': 5, 'board_y': 5, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 734, 'pixel_y': 402, 'board_x': 5, 'board_y': 6, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 734, 'pixel_y': 442, 'board_x': 5, 'board_y': 7, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 734, 'pixel_y': 482, 'board_x': 5, 'board_y': 8, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 734, 'pixel_y': 522, 'board_x': 5, 'board_y': 9, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}],
                                 [{'pixel_x': 774, 'pixel_y': 162, 'board_x': 6, 'board_y': 0, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 774, 'pixel_y': 202, 'board_x': 6, 'board_y': 1, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 774, 'pixel_y': 242, 'board_x': 6, 'board_y': 2, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 774, 'pixel_y': 282, 'board_x': 6, 'board_y': 3, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 774, 'pixel_y': 322, 'board_x': 6, 'board_y': 4, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 774, 'pixel_y': 362, 'board_x': 6, 'board_y': 5, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 774, 'pixel_y': 402, 'board_x': 6, 'board_y': 6, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 774, 'pixel_y': 442, 'board_x': 6, 'board_y': 7, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 774, 'pixel_y': 482, 'board_x': 6, 'board_y': 8, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 774, 'pixel_y': 522, 'board_x': 6, 'board_y': 9, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}],
                                 [{'pixel_x': 814, 'pixel_y': 162, 'board_x': 7, 'board_y': 0, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 814, 'pixel_y': 202, 'board_x': 7, 'board_y': 1, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 814, 'pixel_y': 242, 'board_x': 7, 'board_y': 2, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 814, 'pixel_y': 282, 'board_x': 7, 'board_y': 3, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 814, 'pixel_y': 322, 'board_x': 7, 'board_y': 4, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 814, 'pixel_y': 362, 'board_x': 7, 'board_y': 5, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 814, 'pixel_y': 402, 'board_x': 7, 'board_y': 6, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 814, 'pixel_y': 442, 'board_x': 7, 'board_y': 7, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 814, 'pixel_y': 482, 'board_x': 7, 'board_y': 8, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 814, 'pixel_y': 522, 'board_x': 7, 'board_y': 9, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}],
                                 [{'pixel_x': 854, 'pixel_y': 162, 'board_x': 8, 'board_y': 0, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 854, 'pixel_y': 202, 'board_x': 8, 'board_y': 1, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 854, 'pixel_y': 242, 'board_x': 8, 'board_y': 2, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 854, 'pixel_y': 282, 'board_x': 8, 'board_y': 3, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 854, 'pixel_y': 322, 'board_x': 8, 'board_y': 4, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 854, 'pixel_y': 362, 'board_x': 8, 'board_y': 5, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 854, 'pixel_y': 402, 'board_x': 8, 'board_y': 6, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 854, 'pixel_y': 442, 'board_x': 8, 'board_y': 7, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 854, 'pixel_y': 482, 'board_x': 8, 'board_y': 8, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 854, 'pixel_y': 522, 'board_x': 8, 'board_y': 9, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}],
                                 [{'pixel_x': 894, 'pixel_y': 162, 'board_x': 9, 'board_y': 0, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 894, 'pixel_y': 202, 'board_x': 9, 'board_y': 1, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 894, 'pixel_y': 242, 'board_x': 9, 'board_y': 2, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 894, 'pixel_y': 282, 'board_x': 9, 'board_y': 3, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 894, 'pixel_y': 322, 'board_x': 9, 'board_y': 4, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 894, 'pixel_y': 362, 'board_x': 9, 'board_y': 5, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 894, 'pixel_y': 402, 'board_x': 9, 'board_y': 6, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 894, 'pixel_y': 442, 'board_x': 9, 'board_y': 7, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 894, 'pixel_y': 482, 'board_x': 9, 'board_y': 8, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 894, 'pixel_y': 522, 'board_x': 9, 'board_y': 9, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}]],
                       'topleft': {'pixel_x': 532, 'pixel_y': 160},
                       'targets': []}
    return new_enemy_board


@pytest.fixture()
def player_board_sample():
    player_board_sample = {'tiles': [[{'pixel_x': 94, 'pixel_y': 162, 'board_x': 0, 'board_y': 0, 'is_empty': True, 'is_for_spacing': True, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 94, 'pixel_y': 202, 'board_x': 0, 'board_y': 1, 'is_empty': False, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (0, 0, 155)}, {'pixel_x': 94, 'pixel_y': 242, 'board_x': 0, 'board_y': 2, 'is_empty': False, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (0, 0, 155)}, {'pixel_x': 94, 'pixel_y': 282, 'board_x': 0, 'board_y': 3, 'is_empty': True, 'is_for_spacing': True, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 94, 'pixel_y': 322, 'board_x': 0, 'board_y': 4, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 94, 'pixel_y': 362, 'board_x': 0, 'board_y': 5, 'is_empty': True, 'is_for_spacing': True, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 94, 'pixel_y': 402, 'board_x': 0, 'board_y': 6, 'is_empty': False, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (155, 155, 0)}, {'pixel_x': 94, 'pixel_y': 442, 'board_x': 0, 'board_y': 7, 'is_empty': True, 'is_for_spacing': True, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 94, 'pixel_y': 482, 'board_x': 0, 'board_y': 8, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 94, 'pixel_y': 522, 'board_x': 0, 'board_y': 9, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}],
                                     [{'pixel_x': 134, 'pixel_y': 162, 'board_x': 1, 'board_y': 0, 'is_empty': True, 'is_for_spacing': True, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 134, 'pixel_y': 202, 'board_x': 1, 'board_y': 1, 'is_empty': True, 'is_for_spacing': True, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 134, 'pixel_y': 242, 'board_x': 1, 'board_y': 2, 'is_empty': True, 'is_for_spacing': True, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 134, 'pixel_y': 282, 'board_x': 1, 'board_y': 3, 'is_empty': True, 'is_for_spacing': True, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 134, 'pixel_y': 322, 'board_x': 1, 'board_y': 4, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 134, 'pixel_y': 362, 'board_x': 1, 'board_y': 5, 'is_empty': True, 'is_for_spacing': True, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 134, 'pixel_y': 402, 'board_x': 1, 'board_y': 6, 'is_empty': True, 'is_for_spacing': True, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 134, 'pixel_y': 442, 'board_x': 1, 'board_y': 7, 'is_empty': True, 'is_for_spacing': True, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 134, 'pixel_y': 482, 'board_x': 1, 'board_y': 8, 'is_empty': True, 'is_for_spacing': True, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 134, 'pixel_y': 522, 'board_x': 1, 'board_y': 9, 'is_empty': True, 'is_for_spacing': True, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}],
                                     [{'pixel_x': 174, 'pixel_y': 162, 'board_x': 2, 'board_y': 0, 'is_empty': True, 'is_for_spacing': True, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 174, 'pixel_y': 202, 'board_x': 2, 'board_y': 1, 'is_empty': False, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (155, 155, 0)}, {'pixel_x': 174, 'pixel_y': 242, 'board_x': 2, 'board_y': 2, 'is_empty': True, 'is_for_spacing': True, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 174, 'pixel_y': 282, 'board_x': 2, 'board_y': 3, 'is_empty': True, 'is_for_spacing': True, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 174, 'pixel_y': 322, 'board_x': 2, 'board_y': 4, 'is_empty': True, 'is_for_spacing': True, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 174, 'pixel_y': 362, 'board_x': 2, 'board_y': 5, 'is_empty': True, 'is_for_spacing': True, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 174, 'pixel_y': 402, 'board_x': 2, 'board_y': 6, 'is_empty': True, 'is_for_spacing': True, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 174, 'pixel_y': 442, 'board_x': 2, 'board_y': 7, 'is_empty': True, 'is_for_spacing': True, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 174, 'pixel_y': 482, 'board_x': 2, 'board_y': 8, 'is_empty': False, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (0, 0, 155)}, {'pixel_x': 174, 'pixel_y': 522, 'board_x': 2, 'board_y': 9, 'is_empty': True, 'is_for_spacing': True, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}],
                                     [{'pixel_x': 214, 'pixel_y': 162, 'board_x': 3, 'board_y': 0, 'is_empty': True, 'is_for_spacing': True, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 214, 'pixel_y': 202, 'board_x': 3, 'board_y': 1, 'is_empty': True, 'is_for_spacing': True, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 214, 'pixel_y': 242, 'board_x': 3, 'board_y': 2, 'is_empty': True, 'is_for_spacing': True, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 214, 'pixel_y': 282, 'board_x': 3, 'board_y': 3, 'is_empty': True, 'is_for_spacing': True, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 214, 'pixel_y': 322, 'board_x': 3, 'board_y': 4, 'is_empty': False, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (155, 155, 0)}, {'pixel_x': 214, 'pixel_y': 362, 'board_x': 3, 'board_y': 5, 'is_empty': True, 'is_for_spacing': True, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 214, 'pixel_y': 402, 'board_x': 3, 'board_y': 6, 'is_empty': False, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (155, 155, 0)}, {'pixel_x': 214, 'pixel_y': 442, 'board_x': 3, 'board_y': 7, 'is_empty': True, 'is_for_spacing': True, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 214, 'pixel_y': 482, 'board_x': 3, 'board_y': 8, 'is_empty': False, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (0, 0, 155)}, {'pixel_x': 214, 'pixel_y': 522, 'board_x': 3, 'board_y': 9, 'is_empty': True, 'is_for_spacing': True, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}],
                                     [{'pixel_x': 254, 'pixel_y': 162, 'board_x': 4, 'board_y': 0, 'is_empty': True, 'is_for_spacing': True, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 254, 'pixel_y': 202, 'board_x': 4, 'board_y': 1, 'is_empty': True, 'is_for_spacing': True, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 254, 'pixel_y': 242, 'board_x': 4, 'board_y': 2, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 254, 'pixel_y': 282, 'board_x': 4, 'board_y': 3, 'is_empty': True, 'is_for_spacing': True, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 254, 'pixel_y': 322, 'board_x': 4, 'board_y': 4, 'is_empty': True, 'is_for_spacing': True, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 254, 'pixel_y': 362, 'board_x': 4, 'board_y': 5, 'is_empty': True, 'is_for_spacing': True, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 254, 'pixel_y': 402, 'board_x': 4, 'board_y': 6, 'is_empty': True, 'is_for_spacing': True, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 254, 'pixel_y': 442, 'board_x': 4, 'board_y': 7, 'is_empty': True, 'is_for_spacing': True, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 254, 'pixel_y': 482, 'board_x': 4, 'board_y': 8, 'is_empty': True, 'is_for_spacing': True, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 254, 'pixel_y': 522, 'board_x': 4, 'board_y': 9, 'is_empty': True, 'is_for_spacing': True, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}],
                                     [{'pixel_x': 294, 'pixel_y': 162, 'board_x': 5, 'board_y': 0, 'is_empty': False, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (155, 0, 0)}, {'pixel_x': 294, 'pixel_y': 202, 'board_x': 5, 'board_y': 1, 'is_empty': True, 'is_for_spacing': True, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 294, 'pixel_y': 242, 'board_x': 5, 'board_y': 2, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 294, 'pixel_y': 282, 'board_x': 5, 'board_y': 3, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 294, 'pixel_y': 322, 'board_x': 5, 'board_y': 4, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 294, 'pixel_y': 362, 'board_x': 5, 'board_y': 5, 'is_empty': True, 'is_for_spacing': True, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 294, 'pixel_y': 402, 'board_x': 5, 'board_y': 6, 'is_empty': False, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (0, 0, 155)}, {'pixel_x': 294, 'pixel_y': 442, 'board_x': 5, 'board_y': 7, 'is_empty': False, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (0, 0, 155)}, {'pixel_x': 294, 'pixel_y': 482, 'board_x': 5, 'board_y': 8, 'is_empty': True, 'is_for_spacing': True, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 294, 'pixel_y': 522, 'board_x': 5, 'board_y': 9, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}],
                                     [{'pixel_x': 334, 'pixel_y': 162, 'board_x': 6, 'board_y': 0, 'is_empty': False, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (155, 0, 0)}, {'pixel_x': 334, 'pixel_y': 202, 'board_x': 6, 'board_y': 1, 'is_empty': True, 'is_for_spacing': True, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 334, 'pixel_y': 242, 'board_x': 6, 'board_y': 2, 'is_empty': True, 'is_for_spacing': True, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 334, 'pixel_y': 282, 'board_x': 6, 'board_y': 3, 'is_empty': True, 'is_for_spacing': True, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 334, 'pixel_y': 322, 'board_x': 6, 'board_y': 4, 'is_empty': True, 'is_for_spacing': True, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 334, 'pixel_y': 362, 'board_x': 6, 'board_y': 5, 'is_empty': True, 'is_for_spacing': True, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 334, 'pixel_y': 402, 'board_x': 6, 'board_y': 6, 'is_empty': True, 'is_for_spacing': True, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 334, 'pixel_y': 442, 'board_x': 6, 'board_y': 7, 'is_empty': True, 'is_for_spacing': True, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 334, 'pixel_y': 482, 'board_x': 6, 'board_y': 8, 'is_empty': True, 'is_for_spacing': True, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 334, 'pixel_y': 522, 'board_x': 6, 'board_y': 9, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}],
                                     [{'pixel_x': 374, 'pixel_y': 162, 'board_x': 7, 'board_y': 0, 'is_empty': False, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (155, 0, 0)}, {'pixel_x': 374, 'pixel_y': 202, 'board_x': 7, 'board_y': 1, 'is_empty': True, 'is_for_spacing': True, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 374, 'pixel_y': 242, 'board_x': 7, 'board_y': 2, 'is_empty': False, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (0, 155, 0)}, {'pixel_x': 374, 'pixel_y': 282, 'board_x': 7, 'board_y': 3, 'is_empty': False, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (0, 155, 0)}, {'pixel_x': 374, 'pixel_y': 322, 'board_x': 7, 'board_y': 4, 'is_empty': False, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (0, 155, 0)}, {'pixel_x': 374, 'pixel_y': 362, 'board_x': 7, 'board_y': 5, 'is_empty': True, 'is_for_spacing': True, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 374, 'pixel_y': 402, 'board_x': 7, 'board_y': 6, 'is_empty': False, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (0, 155, 0)}, {'pixel_x': 374, 'pixel_y': 442, 'board_x': 7, 'board_y': 7, 'is_empty': True, 'is_for_spacing': True, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 374, 'pixel_y': 482, 'board_x': 7, 'board_y': 8, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 374, 'pixel_y': 522, 'board_x': 7, 'board_y': 9, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}],
                                     [{'pixel_x': 414, 'pixel_y': 162, 'board_x': 8, 'board_y': 0, 'is_empty': False, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (155, 0, 0)}, {'pixel_x': 414, 'pixel_y': 202, 'board_x': 8, 'board_y': 1, 'is_empty': True, 'is_for_spacing': True, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 414, 'pixel_y': 242, 'board_x': 8, 'board_y': 2, 'is_empty': True, 'is_for_spacing': True, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 414, 'pixel_y': 282, 'board_x': 8, 'board_y': 3, 'is_empty': True, 'is_for_spacing': True, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 414, 'pixel_y': 322, 'board_x': 8, 'board_y': 4, 'is_empty': True, 'is_for_spacing': True, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 414, 'pixel_y': 362, 'board_x': 8, 'board_y': 5, 'is_empty': True, 'is_for_spacing': True, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 414, 'pixel_y': 402, 'board_x': 8, 'board_y': 6, 'is_empty': False, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (0, 155, 0)}, {'pixel_x': 414, 'pixel_y': 442, 'board_x': 8, 'board_y': 7, 'is_empty': True, 'is_for_spacing': True, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 414, 'pixel_y': 482, 'board_x': 8, 'board_y': 8, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 414, 'pixel_y': 522, 'board_x': 8, 'board_y': 9, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}],
                                     [{'pixel_x': 454, 'pixel_y': 162, 'board_x': 9, 'board_y': 0, 'is_empty': True, 'is_for_spacing': True, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 454, 'pixel_y': 202, 'board_x': 9, 'board_y': 1, 'is_empty': True, 'is_for_spacing': True, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 454, 'pixel_y': 242, 'board_x': 9, 'board_y': 2, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 454, 'pixel_y': 282, 'board_x': 9, 'board_y': 3, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 454, 'pixel_y': 322, 'board_x': 9, 'board_y': 4, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 454, 'pixel_y': 362, 'board_x': 9, 'board_y': 5, 'is_empty': True, 'is_for_spacing': True, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 454, 'pixel_y': 402, 'board_x': 9, 'board_y': 6, 'is_empty': False, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (0, 155, 0)}, {'pixel_x': 454, 'pixel_y': 442, 'board_x': 9, 'board_y': 7, 'is_empty': True, 'is_for_spacing': True, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 454, 'pixel_y': 482, 'board_x': 9, 'board_y': 8, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 454, 'pixel_y': 522, 'board_x': 9, 'board_y': 9, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}]],
                           'topleft': {'pixel_x': 92, 'pixel_y': 160},
                           'targets': [(0, 1), (0, 2), (0, 6), (2, 1), (2, 8), (3, 4), (3, 6), (3, 8), (5, 0), (5, 6), (5, 7), (6, 0), (7, 0), (7, 2), (7, 3), (7, 4), (7, 6), (8, 0), (8, 6), (9, 6)]}
    return player_board_sample


@pytest.fixture()
def enemy_board_sample():
    enemy_board_sample = {'tiles': [[{'pixel_x': 534, 'pixel_y': 162, 'board_x': 0, 'board_y': 0, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 534, 'pixel_y': 202, 'board_x': 0, 'board_y': 1, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 534, 'pixel_y': 242, 'board_x': 0, 'board_y': 2, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 534, 'pixel_y': 282, 'board_x': 0, 'board_y': 3, 'is_empty': True, 'is_for_spacing': True, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 534, 'pixel_y': 322, 'board_x': 0, 'board_y': 4, 'is_empty': True, 'is_for_spacing': True, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 534, 'pixel_y': 362, 'board_x': 0, 'board_y': 5, 'is_empty': True, 'is_for_spacing': True, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 534, 'pixel_y': 402, 'board_x': 0, 'board_y': 6, 'is_empty': True, 'is_for_spacing': True, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 534, 'pixel_y': 442, 'board_x': 0, 'board_y': 7, 'is_empty': True, 'is_for_spacing': True, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 534, 'pixel_y': 482, 'board_x': 0, 'board_y': 8, 'is_empty': True, 'is_for_spacing': True, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 534, 'pixel_y': 522, 'board_x': 0, 'board_y': 9, 'is_empty': True, 'is_for_spacing': True, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}],
                                    [{'pixel_x': 574, 'pixel_y': 162, 'board_x': 1, 'board_y': 0, 'is_empty': True, 'is_for_spacing': True, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 574, 'pixel_y': 202, 'board_x': 1, 'board_y': 1, 'is_empty': True, 'is_for_spacing': True, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 574, 'pixel_y': 242, 'board_x': 1, 'board_y': 2, 'is_empty': True, 'is_for_spacing': True, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 574, 'pixel_y': 282, 'board_x': 1, 'board_y': 3, 'is_empty': True, 'is_for_spacing': True, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 574, 'pixel_y': 322, 'board_x': 1, 'board_y': 4, 'is_empty': False, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (0, 155, 0)}, {'pixel_x': 574, 'pixel_y': 362, 'board_x': 1, 'board_y': 5, 'is_empty': False, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (0, 155, 0)}, {'pixel_x': 574, 'pixel_y': 402, 'board_x': 1, 'board_y': 6, 'is_empty': False, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (0, 155, 0)}, {'pixel_x': 574, 'pixel_y': 442, 'board_x': 1, 'board_y': 7, 'is_empty': True, 'is_for_spacing': True, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 574, 'pixel_y': 482, 'board_x': 1, 'board_y': 8, 'is_empty': True, 'is_for_spacing': True, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 574, 'pixel_y': 522, 'board_x': 1, 'board_y': 9, 'is_empty': False, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (155, 155, 0)}],
                                    [{'pixel_x': 614, 'pixel_y': 162, 'board_x': 2, 'board_y': 0, 'is_empty': False, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (0, 155, 0)}, {'pixel_x': 614, 'pixel_y': 202, 'board_x': 2, 'board_y': 1, 'is_empty': False, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (0, 155, 0)}, {'pixel_x': 614, 'pixel_y': 242, 'board_x': 2, 'board_y': 2, 'is_empty': False, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (0, 155, 0)}, {'pixel_x': 614, 'pixel_y': 282, 'board_x': 2, 'board_y': 3, 'is_empty': True, 'is_for_spacing': True, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 614, 'pixel_y': 322, 'board_x': 2, 'board_y': 4, 'is_empty': True, 'is_for_spacing': True, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 614, 'pixel_y': 362, 'board_x': 2, 'board_y': 5, 'is_empty': True, 'is_for_spacing': True, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 614, 'pixel_y': 402, 'board_x': 2, 'board_y': 6, 'is_empty': True, 'is_for_spacing': True, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 614, 'pixel_y': 442, 'board_x': 2, 'board_y': 7, 'is_empty': True, 'is_for_spacing': True, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 614, 'pixel_y': 482, 'board_x': 2, 'board_y': 8, 'is_empty': True, 'is_for_spacing': True, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 614, 'pixel_y': 522, 'board_x': 2, 'board_y': 9, 'is_empty': True, 'is_for_spacing': True, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}],
                                    [{'pixel_x': 654, 'pixel_y': 162, 'board_x': 3, 'board_y': 0, 'is_empty': True, 'is_for_spacing': True, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 654, 'pixel_y': 202, 'board_x': 3, 'board_y': 1, 'is_empty': True, 'is_for_spacing': True, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 654, 'pixel_y': 242, 'board_x': 3, 'board_y': 2, 'is_empty': True, 'is_for_spacing': True, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 654, 'pixel_y': 282, 'board_x': 3, 'board_y': 3, 'is_empty': True, 'is_for_spacing': True, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 654, 'pixel_y': 322, 'board_x': 3, 'board_y': 4, 'is_empty': True, 'is_for_spacing': True, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 654, 'pixel_y': 362, 'board_x': 3, 'board_y': 5, 'is_empty': True, 'is_for_spacing': True, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 654, 'pixel_y': 402, 'board_x': 3, 'board_y': 6, 'is_empty': True, 'is_for_spacing': True, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 654, 'pixel_y': 442, 'board_x': 3, 'board_y': 7, 'is_empty': True, 'is_for_spacing': True, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 654, 'pixel_y': 482, 'board_x': 3, 'board_y': 8, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 654, 'pixel_y': 522, 'board_x': 3, 'board_y': 9, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}],
                                    [{'pixel_x': 694, 'pixel_y': 162, 'board_x': 4, 'board_y': 0, 'is_empty': False, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (155, 155, 0)}, {'pixel_x': 694, 'pixel_y': 202, 'board_x': 4, 'board_y': 1, 'is_empty': True, 'is_for_spacing': True, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 694, 'pixel_y': 242, 'board_x': 4, 'board_y': 2, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 694, 'pixel_y': 282, 'board_x': 4, 'board_y': 3, 'is_empty': True, 'is_for_spacing': True, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 694, 'pixel_y': 322, 'board_x': 4, 'board_y': 4, 'is_empty': False, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (0, 0, 155)}, {'pixel_x': 694, 'pixel_y': 362, 'board_x': 4, 'board_y': 5, 'is_empty': True, 'is_for_spacing': True, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 694, 'pixel_y': 402, 'board_x': 4, 'board_y': 6, 'is_empty': False, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (0, 0, 155)}, {'pixel_x': 694, 'pixel_y': 442, 'board_x': 4, 'board_y': 7, 'is_empty': True, 'is_for_spacing': True, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 694, 'pixel_y': 482, 'board_x': 4, 'board_y': 8, 'is_empty': True, 'is_for_spacing': True, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 694, 'pixel_y': 522, 'board_x': 4, 'board_y': 9, 'is_empty': True, 'is_for_spacing': True, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}],
                                    [{'pixel_x': 734, 'pixel_y': 162, 'board_x': 5, 'board_y': 0, 'is_empty': True, 'is_for_spacing': True, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 734, 'pixel_y': 202, 'board_x': 5, 'board_y': 1, 'is_empty': True, 'is_for_spacing': True, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 734, 'pixel_y': 242, 'board_x': 5, 'board_y': 2, 'is_empty': True, 'is_for_spacing': True, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 734, 'pixel_y': 282, 'board_x': 5, 'board_y': 3, 'is_empty': True, 'is_for_spacing': True, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 734, 'pixel_y': 322, 'board_x': 5, 'board_y': 4, 'is_empty': False, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (0, 0, 155)}, {'pixel_x': 734, 'pixel_y': 362, 'board_x': 5, 'board_y': 5, 'is_empty': True, 'is_for_spacing': True, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 734, 'pixel_y': 402, 'board_x': 5, 'board_y': 6, 'is_empty': False, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (0, 0, 155)}, {'pixel_x': 734, 'pixel_y': 442, 'board_x': 5, 'board_y': 7, 'is_empty': True, 'is_for_spacing': True, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 734, 'pixel_y': 482, 'board_x': 5, 'board_y': 8, 'is_empty': True, 'is_for_spacing': True, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 734, 'pixel_y': 522, 'board_x': 5, 'board_y': 9, 'is_empty': False, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (155, 155, 0)}],
                                    [{'pixel_x': 774, 'pixel_y': 162, 'board_x': 6, 'board_y': 0, 'is_empty': True, 'is_for_spacing': True, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 774, 'pixel_y': 202, 'board_x': 6, 'board_y': 1, 'is_empty': True, 'is_for_spacing': True, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 774, 'pixel_y': 242, 'board_x': 6, 'board_y': 2, 'is_empty': False, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (155, 0, 0)}, {'pixel_x': 774, 'pixel_y': 282, 'board_x': 6, 'board_y': 3, 'is_empty': True, 'is_for_spacing': True, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 774, 'pixel_y': 322, 'board_x': 6, 'board_y': 4, 'is_empty': True, 'is_for_spacing': True, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 774, 'pixel_y': 362, 'board_x': 6, 'board_y': 5, 'is_empty': True, 'is_for_spacing': True, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 774, 'pixel_y': 402, 'board_x': 6, 'board_y': 6, 'is_empty': True, 'is_for_spacing': True, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 774, 'pixel_y': 442, 'board_x': 6, 'board_y': 7, 'is_empty': True, 'is_for_spacing': True, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 774, 'pixel_y': 482, 'board_x': 6, 'board_y': 8, 'is_empty': True, 'is_for_spacing': True, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 774, 'pixel_y': 522, 'board_x': 6, 'board_y': 9, 'is_empty': True, 'is_for_spacing': True, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}],
                                    [{'pixel_x': 814, 'pixel_y': 162, 'board_x': 7, 'board_y': 0, 'is_empty': False, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (155, 155, 0)}, {'pixel_x': 814, 'pixel_y': 202, 'board_x': 7, 'board_y': 1, 'is_empty': True, 'is_for_spacing': True, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 814, 'pixel_y': 242, 'board_x': 7, 'board_y': 2, 'is_empty': False, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (155, 0, 0)}, {'pixel_x': 814, 'pixel_y': 282, 'board_x': 7, 'board_y': 3, 'is_empty': True, 'is_for_spacing': True, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 814, 'pixel_y': 322, 'board_x': 7, 'board_y': 4, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 814, 'pixel_y': 362, 'board_x': 7, 'board_y': 5, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 814, 'pixel_y': 402, 'board_x': 7, 'board_y': 6, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 814, 'pixel_y': 442, 'board_x': 7, 'board_y': 7, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 814, 'pixel_y': 482, 'board_x': 7, 'board_y': 8, 'is_empty': True, 'is_for_spacing': True, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 814, 'pixel_y': 522, 'board_x': 7, 'board_y': 9, 'is_empty': False, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (0, 0, 155)}],
                                    [{'pixel_x': 854, 'pixel_y': 162, 'board_x': 8, 'board_y': 0, 'is_empty': True, 'is_for_spacing': True, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 854, 'pixel_y': 202, 'board_x': 8, 'board_y': 1, 'is_empty': True, 'is_for_spacing': True, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 854, 'pixel_y': 242, 'board_x': 8, 'board_y': 2, 'is_empty': False, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (155, 0, 0)}, {'pixel_x': 854, 'pixel_y': 282, 'board_x': 8, 'board_y': 3, 'is_empty': True, 'is_for_spacing': True, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 854, 'pixel_y': 322, 'board_x': 8, 'board_y': 4, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 854, 'pixel_y': 362, 'board_x': 8, 'board_y': 5, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 854, 'pixel_y': 402, 'board_x': 8, 'board_y': 6, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 854, 'pixel_y': 442, 'board_x': 8, 'board_y': 7, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 854, 'pixel_y': 482, 'board_x': 8, 'board_y': 8, 'is_empty': True, 'is_for_spacing': True, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 854, 'pixel_y': 522, 'board_x': 8, 'board_y': 9, 'is_empty': False, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (0, 0, 155)}],
                                    [{'pixel_x': 894, 'pixel_y': 162, 'board_x': 9, 'board_y': 0, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 894, 'pixel_y': 202, 'board_x': 9, 'board_y': 1, 'is_empty': True, 'is_for_spacing': True, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 894, 'pixel_y': 242, 'board_x': 9, 'board_y': 2, 'is_empty': False, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (155, 0, 0)}, {'pixel_x': 894, 'pixel_y': 282, 'board_x': 9, 'board_y': 3, 'is_empty': True, 'is_for_spacing': True, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 894, 'pixel_y': 322, 'board_x': 9, 'board_y': 4, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 894, 'pixel_y': 362, 'board_x': 9, 'board_y': 5, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 894, 'pixel_y': 402, 'board_x': 9, 'board_y': 6, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 894, 'pixel_y': 442, 'board_x': 9, 'board_y': 7, 'is_empty': True, 'is_for_spacing': False, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 894, 'pixel_y': 482, 'board_x': 9, 'board_y': 8, 'is_empty': True, 'is_for_spacing': True, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}, {'pixel_x': 894, 'pixel_y': 522, 'board_x': 9, 'board_y': 9, 'is_empty': True, 'is_for_spacing': True, 'is_lighted': False, 'hit_result': None, 'color': (3, 54, 73)}]],
                          'topleft': {'pixel_x': 532, 'pixel_y': 160},
                          'targets': [(1, 4), (1, 5), (1, 6), (1, 9), (2, 0), (2, 1), (2, 2), (4, 0), (4, 4), (4, 6), (5, 4), (5, 6), (5, 9), (6, 2), (7, 0), (7, 2), (7, 9), (8, 2), (8, 9), (9, 2)]}
    return enemy_board_sample


def patch_function(module, func: str, output: iter, monkeypatch) -> None:
    """
    Patches output of the given function by creating generator to
    return the next element in the expected output sequence.

    :param module: The name of the module there function situated.
    :param func: The name of the function to patch.
    :param output: The expected output sequence.
    :param monkeypatch: Monkeypatch fixture of the Pytest library.
    :return: None
    """
    def output_generator(given_output):
        for i in given_output:
            yield i

    def get_next_output_item(*args, **kwargs):
        nonlocal patched_output
        return next(patched_output)

    patched_output = output_generator(output)
    monkeypatch.setattr(module, func, get_next_output_item)


@pytest.fixture()
def patch_random_for_player(monkeypatch):
    patch_function(board_generator, 'choose_orientation_randomly',
                   PLAYER_BOARD_ORIENTATIONS, monkeypatch)
    patch_function(board_generator, 'select_random_tile',
                   PLAYER_BOARD_SHIPS, monkeypatch)


@pytest.fixture()
def patch_random_for_enemy(monkeypatch):
    patch_function(board_generator, 'choose_orientation_randomly',
                   ENEMY_BOARD_ORIENTATIONS, monkeypatch)
    patch_function(board_generator, 'select_random_tile',
                   ENEMY_BOARD_SHIPS, monkeypatch)


@pytest.fixture()
def new_ai_data():
    ai_data = {'state': 'search',
               'attack_direction': None,
               'available_moves': [(0, 0), (0, 1), (0, 2), (0, 3), (0, 4), (0, 5), (0, 6), (0, 7), (0, 8), (0, 9),
                                   (1, 0), (1, 1), (1, 2), (1, 3), (1, 4), (1, 5), (1, 6), (1, 7), (1, 8), (1, 9),
                                   (2, 0), (2, 1), (2, 2), (2, 3), (2, 4), (2, 5), (2, 6), (2, 7), (2, 8), (2, 9),
                                   (3, 0), (3, 1), (3, 2), (3, 3), (3, 4), (3, 5), (3, 6), (3, 7), (3, 8), (3, 9),
                                   (4, 0), (4, 1), (4, 2), (4, 3), (4, 4), (4, 5), (4, 6), (4, 7), (4, 8), (4, 9),
                                   (5, 0), (5, 1), (5, 2), (5, 3), (5, 4), (5, 5), (5, 6), (5, 7), (5, 8), (5, 9),
                                   (6, 0), (6, 1), (6, 2), (6, 3), (6, 4), (6, 5), (6, 6), (6, 7), (6, 8), (6, 9),
                                   (7, 0), (7, 1), (7, 2), (7, 3), (7, 4), (7, 5), (7, 6), (7, 7), (7, 8), (7, 9),
                                   (8, 0), (8, 1), (8, 2), (8, 3), (8, 4), (8, 5), (8, 6), (8, 7), (8, 8), (8, 9),
                                   (9, 0), (9, 1), (9, 2), (9, 3), (9, 4), (9, 5), (9, 6), (9, 7), (9, 8), (9, 9)],
               'hit_moves': [],
               'available_directions': ['up', 'down', 'left', 'right'],
               'ships_on_board_by_size': [4, 3, 3, 2, 2, 2, 1, 1, 1, 1]}
    return ai_data


@pytest.fixture()
def first_step_ai_data():
    ai_data = {'state': 'attack',
               'attack_direction': None,
               'available_moves': [(0, 0), (0, 1), (0, 2), (0, 3), (0, 4), (0, 5), (0, 6), (0, 7), (0, 8), (0, 9),
                                   (1, 0), (1, 1), (1, 2), (1, 3), (1, 4), (1, 6), (1, 7), (1, 8), (1, 9),
                                   (2, 0), (2, 1), (2, 2), (2, 3), (2, 4), (2, 5), (2, 6), (2, 7), (2, 8), (2, 9),
                                   (3, 0), (3, 1), (3, 2), (3, 3), (3, 4), (3, 5), (3, 6), (3, 7), (3, 8), (3, 9),
                                   (4, 0), (4, 1), (4, 2), (4, 3), (4, 4), (4, 5), (4, 6), (4, 7), (4, 8), (4, 9),
                                   (5, 0), (5, 1), (5, 2), (5, 3), (5, 4), (5, 5), (5, 6), (5, 8), (5, 9),
                                   (6, 0), (6, 1), (6, 2), (6, 3), (6, 4), (6, 5), (6, 6), (6, 7), (6, 8), (6, 9),
                                   (7, 0), (7, 1), (7, 2), (7, 3), (7, 4), (7, 5), (7, 7), (7, 8), (7, 9),
                                   (8, 0), (8, 1), (8, 2), (8, 3), (8, 4), (8, 5), (8, 6), (8, 7), (8, 8),
                                   (9, 0), (9, 1), (9, 2), (9, 3), (9, 4), (9, 5), (9, 6), (9, 7), (9, 9)],
               'hit_moves': [(9, 8)],
               'available_directions': ['up', 'down', 'left', 'right'],
               'ships_on_board_by_size': [4, 3, 3, 2, 2, 2, 1, 1, 1, 1]}
    return ai_data


@pytest.fixture()
def patch_random_for_ai(monkeypatch):
    patch_function(ai, 'choose_random_direction', AI_ATTACK_DIRECTIONS,
                   monkeypatch)
    patch_function(ai, 'make_random_move', AI_MOVES, monkeypatch)
